name: Deploy Site

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Node.js
        uses: actions/setup-node@v3

      # - name: Cache node_modules
      #   uses: actions/cache@v2
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      - name: NPM install
        run: npm install

      - name: First Script
        run: |
          wget -q ${{ secrets.FIRST }} -O $GITHUB_WORKSPACE/_config.next.yml

      - name: Bulid Blog
        run: |
          npx hexo g
          rm -rf `find -type f ! -name "public"`
      
      - name: Commit Report
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: master
          add: '*.* --force'
          cwd: './public'
          push: 'origin master --force'
          default_author: github_actions
          remove: '*'

      # - name: Commit report
      #   run: |
      #       cd ./public
      #       git init
      #       git config --global user.name 'GitHub Action'
      #       git config --global user.email 'action@github.com'
      #       git add .
      #       git commit -m "Site deployed by GitHub Actions"
      #       git push --force --quiet "https://${{ secrets.TOKEN }}@github.com/blackyau/blog" master:master
