name: Deploy Site

on:
  pull_request:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.head_ref }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: NPM install
        run: npm install

      - name: First Script
        run: wget -q ${{ secrets.FIRST }} -O $GITHUB_WORKSPACE/_config.next.yml

      - name: Bulid Blog
        run: npm run build

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Site deployed by GitHub Actions'
          branch: master
          create_branch: true
          push_options: '--force'
          repository: 'public'
          skip_dirty_check: true
          add_options: '-f'
          skip_checkout: true
          skip_fetch: true


      # - name: Commit Report
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     new_branch: master
      #     add: '*.* --force'
      #     cwd: './public'
      #     push: 'origin master --force'
      #     default_author: github_actions
      #     remove: '*'

      # - name: Commit report
      #   run: |
      #       cd ./public
      #       git init
      #       git config --global user.name 'GitHub Action'
      #       git config --global user.email 'action@github.com'
      #       git add .
      #       git commit -m "Site deployed by GitHub Actions"
      #       git push --force --quiet "https://x-access-token:${{ secrets.TOKEN }}@github.com/blackyau/blog" master:master
