name: Deploy Site

on:
  pull_request:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: NPM install
        run: npm install

      - name: First Script
        run: wget -q ${{ secrets.FIRST }} -O $GITHUB_WORKSPACE/_config.next.yml

      - name: Bulid Blog
        run: npm run build
      
      - name: Fix post canonical
        run: |
          find public -type f -name "*.html" | while read -r file; do
            sed -i 's|<link rel="canonical" href="\([^"]*\)\.html">|<link rel="canonical" href="\1">|g' "$file"
            echo "处理文件: $file"
          done
          echo "所有 HTML 文件处理完成"
        shell: bash

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: public
          create_branch: true
          push_options: '--force'
          repository: 'public'
          skip_dirty_check: true
          add_options: '-f'
          skip_checkout: true
          skip_fetch: true
